name: AWS ECR

on:
  release:
    types:
      - published
      

jobs:
  
  # Build and push to all ECR regions
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        aws-region: [us-east-1]

    steps:

      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: {{ matrix.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Update RELEASE_TAG with release version
        run: |
          echo ::set-env name=RELEASE_TAG::${GITHUB_REF##*/}

      - name: Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: node-app
          # RELEASE_TAG: ${GITHUB_REF##*/}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:stable
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:stable