name: Docker build

on:
  push:
    branches:
      - master
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Update IMAGE_TAG with shorter commit id
      run:  echo ::set-env name=IMAGE_TAG::$(git rev-parse --short "$GITHUB_SHA")

    - name: Docker build
      run: docker build -t node-app:$IMAGE_TAG .
