name: Docker hub

on:
  release:
    types:
      - published
      

jobs:

  # Build and push to all ECR regions
  Build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Update RELEASE_TAG with release version
        run: |
          echo ::set-env name=RELEASE_TAG::${GITHUB_REF##*/}

      - name: Login to DockerHub Registry
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Push to hub
        env:
          ECR_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
          ECR_REPOSITORY: node-app
          # RELEASE_TAG: ${GITHUB_REF##*/}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$RELEASE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:stable
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:stable