name: Github API

on:
  release:
    types:
      - prereleased

jobs:
  curl:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # Runs a set of commands using the runners shell
    - name: Query the latest release using API
      run: |
       release=$(curl -s \
          --url https://api.github.com/repos/$GITHUB_REPOSITORY/releases/latest \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' | jq ".tag_name")
       echo ::set-env name=RELEASE_TAG::$(echo "${release//\"}")

    # Runs a single command using the runners shell
    - name: Print lates release version
      run: echo 'The latest release is - $RELEASE_TAG'
